spring:
  application:
    name: football-system

  # 1. Java 25 Virtual Threads 
  threads:
    virtual:
      enabled: true

  # 2. Database Configuration
  datasource:
    # Lưu ý: Nếu dùng Docker Compose Support, Spring có thể tự nhận diện, 
    url: jdbc:mysql://localhost:3306/football_booking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mixisql123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 3. JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # 4. Docker Compose Support 
  docker:
    compose:
      enabled: true
      file: ../../../compose.yaml # Đảm bảo đường dẫn này trỏ đúng đến file compose.yaml
      lifecycle-management: start_and_stop # Tự bật DB khi chạy App, tự tắt khi stop App
      readiness:
        tcp:
          host: localhost
          port: 3306

  # 5. SQL Initialization (Tùy chọn)
  sql:
    init:
      mode: never # Đổi thành 'always' nếu bạn có file schema.sql hoặc data.sql muốn chạy tự động

server:
  port: 8080
  servlet:
    context-path: /api/v1

application:
  security:
    jwt:
      # Sẽ đổi sau khi deploy thật
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000 
      refresh-token:
        expiration: 604800000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO
    com.kstn.group4.backend: DEBUG